default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 
  username: postgres
  password: Waithira2013

development:
  <<: *default
  database: hello_rails_react_development

test:
  <<: *default
  database: hello_rails_react_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: hello_rails_react_production
  username: hello_rails_react
  password: <%= ENV["HELLO_RAILS_REACT_DATABASE_PASSWORD"] %>
